version: "3.8"

services:
    app:
        build: .
        ports:
            - "8080:80"
        environment:
            - DB_HOST=db
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - DB_DATABASE=mydatabase
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydatabase
        volumes:
            - db_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
