version: "3.8"

services:
    # Laravel App Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel

    # MySQL Service
    mysql:
        image: mysql:5.7
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: desafio_digitro_sti
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
